export const SERVICES = {
  API_GATEWAY: 'API_GATEWAY',
  AUTH_SERVICE: 'AUTH_SERVICE',
  PRODUCTS_SERVICE: 'PRODUCTS_SERVICE',
  CATALOG_SERVICE: 'CATALOG_SERVICE',
  SEARCH_SERVICE: 'SEARCH_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  MEDIA_SERVICE: 'MEDIA_SERVICE',
} as const;

export const SERVICES_PORTS = {
  API_GATEWAY: 3000,
  AUTH_SERVICE: 3001,
  PRODUCTS_SERVICE: 3002,
  SEARCH_SERVICE: 3003,
  CATALOG_SERVICE: 3004,
  NOTIFICATIONS_SERVICE: 3005,
  MEDIA_SERVICE: 3006,
} as const;
